import { Processor } from './processor.js';
import { Icons } from './icons.js';
const $=s=>document.querySelector(s), setIcon=(id,fn)=>{const e=$('#'+id);if(e)e.innerHTML=fn();};
['upload','help','file','key','shield','bolt','layers'].forEach(k=>setIcon(k==='upload'?'upload-icon':k==='file'?'file-icon':k==='key'?'key-icon':k+'-icon',Icons[k]));
setIcon('decrypt-icon',Icons.bolt); setIcon('help-icon',Icons.help);
let state={file:null,blob:null,usedManual:false,theme:localStorage.getItem('mcxor_theme')||'dark',manual:''};
const body=document.documentElement; const modal=$('#modal');
function theme(){body.dataset.theme=state.theme;localStorage.setItem('mcxor_theme',state.theme);setIcon('theme',state.theme==='dark'?Icons.sun:Icons.moon);}
function showModal(type){const content=type==='about'?'<span class="section-kicker">MCXOR / ABOUT</span><h2>本地世界修复实验室</h2><p>一个纯浏览器端的 Minecraft 存档解密工具。不会请求外部接口，不包含广告、跟踪器或第三方监听代码。</p><p class="muted">解密算法参考 XOR-MC-Archive-Decrypt。全部数据只存在于当前页面内。</p>':'<span class="section-kicker">RESTORATION FLOW</span><h2>三步恢复你的世界</h2><ol><li>拖入或选择一个 .zip 存档。</li><li>工具会检查目录与密钥，并在需要时请求手动密钥。</li><li>解密完成后下载新的 .mcworld 文件。</li></ol><p class="muted">浏览器本地处理，不会上传文件。所有图标均为内联 SVG。</p>';$('#modal-content').innerHTML=content;modal.showModal();}
function setFile(file){if(!file?.name.toLowerCase().endsWith('.zip'))return showResult('error','仅支持 .zip 格式的存档文件');state.file=file;$('#file-name').textContent=file.name;$('#file-size').textContent=Processor.formatSize(file.size);$('#file-card').classList.remove('hidden');$('#decrypt-button').disabled=false;$('#result').classList.add('hidden');}
function clear(){state.file=null;state.blob=null;$('#file-input').value='';$('#file-card').classList.add('hidden');$('#key-box').classList.add('hidden');$('#decrypt-button').disabled=true;$('#result').classList.add('hidden');}
function showResult(type,data){const el=$('#result');el.className='result '+type;el.classList.remove('hidden');if(type==='error'){el.innerHTML=`<div class="result-title">${Icons.error()}<b>解密未完成</b></div><p>${data}</p>`;return;}el.innerHTML=`<div class="result-title">${Icons.check()}<b>世界已恢复</b><span class="result-tag">READY TO DOWNLOAD</span></div><div class="stats"><span><b>${data.count}</b><small>已解密文件</small></span><span><b>${data.total}</b><small>总文件数</small></span><span><b>${data.duration}s</b><small>处理耗时</small></span></div><div class="key-result"><code>${data.key}</code><button id="copy-key">复制密钥</button></div><button class="download-button" id="download">${Icons.download()}下载 .mcworld</button>`;$('#copy-key').onclick=()=>navigator.clipboard?.writeText(data.key);$('#download').onclick=()=>download();}
function progress(p,status,path=''){ $('#progress-area').classList.remove('hidden');$('#progress-bar').style.width=p+'%';$('#progress-value').textContent=p+'%';$('#progress-status').textContent=status;$('#progress-file').textContent=path||'正在处理世界数据'; }
async function decrypt(){if(!state.file)return;const btn=$('#decrypt-button');btn.disabled=true;$('#result').classList.add('hidden');const start=performance.now();try{const manual=$('#manual-key').value.trim();const data=await Processor.decrypt(state.file,manual,(p,s,path)=>progress(p,s,path));if(data.issues.some(x=>x[0].includes('密钥'))&&!manual){$('#key-box').classList.remove('hidden');}state.blob=data.blob;state.usedManual=data.usedManual;showResult('success',{...data,duration:((performance.now()-start)/1000).toFixed(2)});progress(100,'完成');}catch(e){showResult('error',e.message);progress(0,'等待任务');}finally{btn.disabled=!state.file;}}
function download(){if(!state.blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(state.blob);a.download='Decrypted.mcworld';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),300);}
$('#drop-zone').onclick=()=>$('#file-input').click();$('#drop-zone').ondragover=e=>{e.preventDefault();$('#drop-zone').classList.add('dragging')};$('#drop-zone').ondragleave=()=>$('#drop-zone').classList.remove('dragging');$('#drop-zone').ondrop=e=>{e.preventDefault();$('#drop-zone').classList.remove('dragging');setFile(e.dataTransfer.files[0])};$('#file-input').onchange=e=>setFile(e.target.files[0]);$('#manual-key').oninput=e=>e.target.value=e.target.value.replace(/[^0-9a-f]/gi,'').slice(0,16);$('#decrypt-button').onclick=decrypt;
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='theme'){state.theme=state.theme==='dark'?'light':'dark';theme();}if(action==='help')showModal('help');if(action==='about')showModal('about');if(action==='clear')clear();if(action==='close')modal.close();});
$('#drop-zone').onkeydown=e=>{if(e.key==='Enter'||e.key===' ')$('#file-input').click()};theme();

// Canvas 雨夜：雨丝与玻璃水珠均由当前位置、速度和重力实时计算
const rainCanvas=$('#rain-canvas'), glassCanvas=$('#glass-canvas'), rainCtx=rainCanvas.getContext('2d'), glassCtx=glassCanvas.getContext('2d');
let drops=[], beads=[]; const resizeRain=()=>{const d=devicePixelRatio||1; for(const c of [rainCanvas,glassCanvas]){c.width=innerWidth*d;c.height=innerHeight*d;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';}rainCtx.setTransform(d,0,0,d,0,0);glassCtx.setTransform(d,0,0,d,0,0);};
function seedRain(){drops=Array.from({length:Math.min(260,Math.floor(innerWidth/5))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,len:10+Math.random()*27,v:8+Math.random()*13,a:.12+Math.random()*.35}));beads=Array.from({length:Math.min(34,Math.floor(innerWidth/32))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight*.85,r:1.8+Math.random()*4,v:.2+Math.random()*.7,life:Math.random()*100}));}
function animateRain(){const d=devicePixelRatio||1; rainCtx.clearRect(0,0,innerWidth,innerHeight);rainCtx.lineWidth=.65;for(const r of drops){r.y+=r.v;r.x-=.38;if(r.y>innerHeight+40){r.y=-r.len;r.x=Math.random()*innerWidth;}rainCtx.strokeStyle=`rgba(174,224,255,${r.a})`;rainCtx.beginPath();rainCtx.moveTo(r.x,r.y);rainCtx.lineTo(r.x-1.8,r.y+r.len);rainCtx.stroke();}glassCtx.clearRect(0,0,innerWidth,innerHeight);for(const b of beads){b.life++;b.y+=b.v;b.x+=Math.sin(b.life*.025)*.08;if(b.y>innerHeight*.96||b.x<0||b.x>innerWidth){b.y=Math.random()*innerHeight*.45;b.x=Math.random()*innerWidth;b.life=0;}const g=glassCtx.createRadialGradient(b.x-b.r*.35,b.y-b.r*.4,.2,b.x,b.y,b.r*1.7);g.addColorStop(0,'rgba(255,255,255,.75)');g.addColorStop(.25,'rgba(180,235,255,.3)');g.addColorStop(1,'rgba(110,196,240,0)');glassCtx.fillStyle=g;glassCtx.beginPath();glassCtx.arc(b.x,b.y,b.r*1.7,0,Math.PI*2);glassCtx.fill();glassCtx.strokeStyle='rgba(214,249,255,.4)';glassCtx.lineWidth=.45;glassCtx.beginPath();glassCtx.arc(b.x,b.y,b.r,0,Math.PI*2);glassCtx.stroke();}requestAnimationFrame(animateRain);}
addEventListener('resize',()=>{resizeRain();seedRain()},{passive:true});resizeRain();seedRain();animateRain();
