import { Crypto } from './crypto.js';
const size = b => { if(!b)return '0 B'; const units=['B','KB','MB','GB'], i=Math.min(3,Math.floor(Math.log(b)/Math.log(1024))); return `${(b/1024**i).toFixed(i?2:0)} ${units[i]}`; };
export const Processor = {
  formatSize:size,
  nested(zip){ const files=Object.keys(zip.files).filter(p=>!zip.files[p].dir); if(!files.length||files.some(p=>!p.includes('/')))return false; return new Set(files.map(p=>p.split('/')[0])).size===1; },
  async flatten(zip){ const out=new JSZip(), root=Object.keys(zip.files).find(p=>!zip.files[p].dir).split('/')[0]; for(const path in zip.files){const f=zip.files[path];if(!f.dir){const data=await f.async('uint8array');out.file(path.startsWith(root+'/')?path.slice(root.length+1):path,data);}}return out; },
  issues(zip){ const files=Object.keys(zip.files), db=files.filter(f=>f.startsWith('db/')), issues=[]; if(!files.includes('level.dat')&&!files.includes('level.dat_old'))issues.push(['缺少 level.dat','可能导致解密失败或存档数据丢失']); if(!files.includes('levelname.txt'))issues.push(['缺少 levelname.txt','可能导致解密失败或存档数据丢失']); if(!db.length)issues.push(['缺少 db 文件夹','无法进行解密操作']); else {if(!db.some(f=>f.endsWith('.ldb')))issues.push(['缺少 .ldb 文件','解密后存档可能不完整']);if(!db.some(f=>f.endsWith('CURRENT'))||!db.some(f=>/MANIFEST-\d+/.test(f)))issues.push(['缺少密钥文件','需要手动输入密钥']);} return issues; },
  async decrypt(file,manualKey,onProgress){ let zip=await JSZip.loadAsync(await file.arrayBuffer()); onProgress(18,'解压存档'); if(this.nested(zip)){zip=await this.flatten(zip);onProgress(30,'整理目录结构');} ['behavior_packs/','netease_config/','resource_packs/'].forEach(f=>zip.remove(f)); const issues=this.issues(zip); let key=null; const db=Object.keys(zip.files).filter(p=>p.startsWith('db/')); const mf=db.find(p=>/MANIFEST-\d+/.test(p)), cf=db.find(p=>p.endsWith('CURRENT')); if(mf&&cf)key=Crypto.deriveKey(mf.split('/').pop(),await zip.file(cf).async('uint8array')); const usedManual=!key; if(!key){if(!/^[0-9a-fA-F]{16}$/.test(manualKey||'')){const error=Error('无法获取解密密钥，请输入 16 位十六进制密钥');error.code='KEY_REQUIRED';throw error;}key=Crypto.hexToBytes(manualKey);} onProgress(48,'读取解密密钥'); const out=new JSZip(); let count=0, total=Object.values(zip.files).filter(f=>!f.dir).length, n=0, lastError=null; for(const path in zip.files){const f=zip.files[path];if(f.dir)continue;const data=await f.async('uint8array');try{if(path.startsWith('db/')&&Crypto.isEncrypted(data)){out.file(path,Crypto.decrypt(data,key));count++;}else out.file(path,data);}catch(e){lastError=e;out.file(path,data);}n++;onProgress(50+Math.round(n/total*43),'解密文件',path);} if(usedManual&&(lastError||count===0))throw Error('手动密钥可能不正确，解密出现错误'); onProgress(95,'重新打包'); const blob=await out.generateAsync({type:'blob',compression:'STORE'}); return {blob,count,total,key:Crypto.bytesToHex(key),usedManual,issues}; }
};
